### ISSUE TITLE
Support Identity Provider (IdP) Authentication

### ISSUE THREAD

**Issue by idoki-boxycharm** [snowflakedb/snowflake-sqlalchemy#115]
Library does not support SSO (single sign on) authentication from IdP such as Okta. This authentication method becomes widespread in organizations, supporting it would make the library usable for this use-case.

The SnowFlake [python connector](https://docs.snowflake.net/manuals/user-guide/python-connector-example.html#connecting-using-federated-authentication) supports it out-of-the-box and can be relied on.

**Comment by smtakeda** [comment]
`authenticator` parameter can be specified in `connect_args` parameter in `create_engine` method.
```
engine = create_engine(URL(
    account='ACCOUNT',
    user='OKTA_USER',
    password='OKTA_PASSWORD',
    ),
    connect_args={
        'authenticator': 'https://something.okta.com/',
        },
    )
connection = engine.connect()
```

**Comment by Jorne0** [comment]
Perhaps i just don't understand, but I don't think this is solved. My organization doesn't allow user passwords on snowflake accounts. The snowsql external browser authentication works fine but in the above approach for sqlalchemy I still need to provide a password and when I provide my okta password i get a database error saying my password is incorrect (making me think it's sending that password to snowflake rather than okta). How do I connect to snowflake with sqlalchemy using okta without a password (like snowsql)?
Thank you, ~Jorne0

**Comment by MichaelFishmanOD** [comment]
@Jorne0
My organization uses SAML with externalbrowser authentication and no password. The following works for me:

```engine = create_engine(URL(
    account='ACCOUNT',
    user='EMAIL',
    ),
    connect_args={
        'authenticator': 'externalbrowser',
        },
    )```

**Comment by bryanpost** [comment]
@MichaelFishmanOD I get 
`sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 251006: Password is empty`

when using your example...
