### ISSUE TITLE
SNOW-930985: Add support for SQLAlchemy 2

### ISSUE THREAD

**Issue by Ovsyanka83** [snowflakedb/snowflake-sqlalchemy#451]
## What is the current behavior?

You can't install snowflake-sqlalchemy with the second version of sqlalchemy

## What is the desired behavior?
To install snowflake-sqlalchemy with the second version of sqlalchemy

## How would this improve `snowflake-connector-python`?

It would allow you to use all improvements from sqlalchemy 2. To me, the most important ones are the type hinting improvements but there is a lot more.

**Comment by sfc-gh-achandrasekaran** [comment]
@Ovsyanka83 we are aware of this request. It is in our backlog and will be prioritized in the next couple of quarters

**Comment by sk-** [comment]
@sfc-gh-achandrasekaran why was this issue closed if it's not yet resolved?

Also, could you share a better estimate. Do you mean in the next couple of quarters you will start discussing the priority or that in the next couple of quarters you will deliver. Either way taking so much time to bring your package up to date with their dependencies is quite unacceptable.

**Comment by sfc-gh-achandrasekaran** [comment]
@sk- apologies. I closed it because we are already tracking this using https://github.com/snowflakedb/snowflake-sqlalchemy/issues/452

We will start working on this in the next couple of quarters. We totally get the priority of this ask but we also need to balance this with other competing customer asks/priorities.
